language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run prepublishOnly

deploy:
  - provider: script
    script: npm run release
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: master
