version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ./.npmrc
            - run: npm run prepublishOnly
            - run: npm run release
workflows:
  release:
    jobs:
      - release
